# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
# Create random tensor
random_tensor = torch.rand(7, 7)
print(random_tensor)
print(f"Shape of the tensor: {random_tensor.shape}")

tensor([[0.8285, 0.3915, 0.3108, 0.1318, 0.1980, 0.7492, 0.1698],
        [0.9364, 0.9692, 0.4974, 0.4459, 0.2014, 0.6244, 0.8448],
        [0.9185, 0.9123, 0.8009, 0.4984, 0.7727, 0.6063, 0.1539],
        [0.2073, 0.3404, 0.0546, 0.0037, 0.0244, 0.6726, 0.1731],
        [0.9240, 0.0391, 0.6330, 0.5496, 0.5156, 0.5077, 0.0463],
        [0.6655, 0.5064, 0.5953, 0.9929, 0.6099, 0.6526, 0.4224],
        [0.7580, 0.4252, 0.0239, 0.7848, 0.0886, 0.2530, 0.8795]])
Shape of the tensor: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)
print(random_tensor2)
print(f"Shape of the tensor: {random_tensor2.shape}")

# Perform matrix multiplication
transposed_tensor= torch.transpose(random_tensor2, 0, 1)
print(transposed_tensor)
print(f"Shape of the tensor: {transposed_tensor.shape}")

result = torch.matmul(random_tensor, transposed_tensor)
print(result)

tensor([[0.7621, 0.3885, 0.1739, 0.8032, 0.6546, 0.0560, 0.4893]])
Shape of the tensor: torch.Size([1, 7])
tensor([[0.7621],
        [0.3885],
        [0.1739],
        [0.8032],
        [0.6546],
        [0.0560],
        [0.4893]])
Shape of the tensor: torch.Size([7, 1])
tensor([[1.1980],
        [2.1150],
        [2.2091],
        [0.4410],
        [1.6596],
        [2.2474],
        [1.8799]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed

torch.manual_seed(0)

# Create two random tensors

random_tensor=torch.rand(7,7)
print(random_tensor)
print(f"Shape of the tensor: {random_tensor.shape}")

random_tensor2=torch.rand(1,7)
print(random_tensor2)
print(f"Shape of the tensor: {random_tensor2.shape}")

transposed_tensor = torch.transpose(random_tensor2, 0, 1)
print(transposed_tensor)
print(f"Shape of the tensor: {transposed_tensor.shape}")
# Matrix multiply tensors
result = torch.matmul(random_tensor, transposed_tensor)
print(result)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Shape of the tensor: torch.Size([7, 7])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
Shape of the tensor: torch.Size([1, 7])
tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])
Shape of the tensor: torch.Size([7, 1])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU

import torch

# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    # Set the seed for the current GPU
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234.")
else:
    print("CUDA not available. Cannot set GPU seed.")

# Note for multiple GPUs, you would typically use:
# torch.cuda.manual_seed_all(1234)

GPU random seed set to 1234.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [2]:
import torch
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print("Device:", device)
# Create two random tensors on GPU
tensor1=torch.rand(2,3).to(device)
tensor2=torch.rand(2,3).to(device)
print(tensor1)
print(tensor2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [3]:
#### TRnaspose --> tenosr.T ###
# Perform matmul on tensor_A and tensor_B
result =torch.matmul(tensor1,tensor2.T)
print(result)
print(result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [4]:
# Find max
max=torch.max(result)
print(max)
# Find min
min = torch.min(result)
print(min)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [5]:
# Find arg max
argmax= torch.argmax(result)
print(result)

# Find arg min
argmin=torch.argmin(result)
print(argmin)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
seed = torch.manual_seed(7)

# Create random tensor

tensor1=torch.rand(1,1,1,10)

print(tensor1)
print(tensor1.shape)

# Remove single dimensions
#### The .squeeze() method automatically removes all single dimensions  ####
tensor2=tensor1.squeeze()

# Print out tensors and their shapes

print(tensor2)
print(tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
